# Generated by Django 4.2.15 on 2024-11-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationscore',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
