# Generated by Django 4.2.15 on 2024-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0005_registrationkey_score_registration_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationkey',
            name='key',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
