# Generated by Django 4.2.15 on 2024-11-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0006_alter_registrationkey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
