# Generated by Django 4.2.15 on 2024-11-18 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translate_app', '0008_remove_score_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='registration_key',
        ),
        migrations.AlterField(
            model_name='registrationkey',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='是否已使用'),
        ),
        migrations.AlterField(
            model_name='registrationkey',
            name='key',
            field=models.CharField(max_length=512, unique=True, verbose_name='注册密钥'),
        ),
        migrations.AlterField(
            model_name='score',
            name='original_text',
            field=models.TextField(verbose_name='原文'),
        ),
        migrations.AlterField(
            model_name='score',
            name='review',
            field=models.TextField(verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='score',
            name='translated_text',
            field=models.TextField(verbose_name='译文'),
        ),
        migrations.AlterField(
            model_name='score',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='score',
            name='year',
            field=models.IntegerField(verbose_name='年份'),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translate_app.registrationkey', verbose_name='注册密钥')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL, verbose_name='用户信息')),
            ],
        ),
    ]
